// Generated by scripts/sync-herdr-themes.mjs from Herdr src/app/state.rs.
// Temporary compatibility copy until Herdr exposes its resolved runtime palette.

import type { ResolvedThemeSnapshot } from "./model.js";

const themes: Record<string, ResolvedThemeSnapshot> = {
  "catppuccin": {
    "name": "catppuccin",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 137,
        "g": 180,
        "b": 250
      },
      "panel_bg": {
        "r": 24,
        "g": 24,
        "b": 37
      },
      "surface0": {
        "r": 49,
        "g": 50,
        "b": 68
      },
      "surface1": {
        "r": 69,
        "g": 71,
        "b": 90
      },
      "surface_dim": {
        "r": 30,
        "g": 30,
        "b": 46
      },
      "overlay0": {
        "r": 108,
        "g": 112,
        "b": 134
      },
      "overlay1": {
        "r": 127,
        "g": 132,
        "b": 156
      },
      "text": {
        "r": 205,
        "g": 214,
        "b": 244
      },
      "subtext0": {
        "r": 166,
        "g": 173,
        "b": 200
      },
      "mauve": {
        "r": 203,
        "g": 166,
        "b": 247
      },
      "green": {
        "r": 166,
        "g": 227,
        "b": 161
      },
      "yellow": {
        "r": 249,
        "g": 226,
        "b": 175
      },
      "red": {
        "r": 243,
        "g": 139,
        "b": 168
      },
      "blue": {
        "r": 137,
        "g": 180,
        "b": 250
      },
      "teal": {
        "r": 148,
        "g": 226,
        "b": 213
      },
      "peach": {
        "r": 250,
        "g": 179,
        "b": 135
      }
    }
  },
  "catppuccin-latte": {
    "name": "catppuccin-latte",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 30,
        "g": 102,
        "b": 245
      },
      "panel_bg": {
        "r": 239,
        "g": 241,
        "b": 245
      },
      "surface0": {
        "r": 204,
        "g": 208,
        "b": 218
      },
      "surface1": {
        "r": 188,
        "g": 192,
        "b": 204
      },
      "surface_dim": {
        "r": 230,
        "g": 233,
        "b": 239
      },
      "overlay0": {
        "r": 156,
        "g": 160,
        "b": 176
      },
      "overlay1": {
        "r": 140,
        "g": 143,
        "b": 161
      },
      "text": {
        "r": 76,
        "g": 79,
        "b": 105
      },
      "subtext0": {
        "r": 108,
        "g": 111,
        "b": 133
      },
      "mauve": {
        "r": 136,
        "g": 57,
        "b": 239
      },
      "green": {
        "r": 64,
        "g": 160,
        "b": 43
      },
      "yellow": {
        "r": 223,
        "g": 142,
        "b": 29
      },
      "red": {
        "r": 210,
        "g": 15,
        "b": 57
      },
      "blue": {
        "r": 30,
        "g": 102,
        "b": 245
      },
      "teal": {
        "r": 23,
        "g": 146,
        "b": 153
      },
      "peach": {
        "r": 254,
        "g": 100,
        "b": 11
      }
    }
  },
  "tokyo-night": {
    "name": "tokyo-night",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 122,
        "g": 162,
        "b": 247
      },
      "panel_bg": {
        "r": 26,
        "g": 27,
        "b": 38
      },
      "surface0": {
        "r": 36,
        "g": 40,
        "b": 59
      },
      "surface1": {
        "r": 65,
        "g": 72,
        "b": 104
      },
      "surface_dim": {
        "r": 26,
        "g": 27,
        "b": 38
      },
      "overlay0": {
        "r": 86,
        "g": 95,
        "b": 137
      },
      "overlay1": {
        "r": 105,
        "g": 113,
        "b": 150
      },
      "text": {
        "r": 192,
        "g": 202,
        "b": 245
      },
      "subtext0": {
        "r": 169,
        "g": 177,
        "b": 214
      },
      "mauve": {
        "r": 187,
        "g": 154,
        "b": 247
      },
      "green": {
        "r": 158,
        "g": 206,
        "b": 106
      },
      "yellow": {
        "r": 224,
        "g": 175,
        "b": 104
      },
      "red": {
        "r": 247,
        "g": 118,
        "b": 142
      },
      "blue": {
        "r": 122,
        "g": 162,
        "b": 247
      },
      "teal": {
        "r": 125,
        "g": 207,
        "b": 255
      },
      "peach": {
        "r": 255,
        "g": 158,
        "b": 100
      }
    }
  },
  "tokyo-night-day": {
    "name": "tokyo-night-day",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 46,
        "g": 125,
        "b": 233
      },
      "panel_bg": {
        "r": 225,
        "g": 226,
        "b": 231
      },
      "surface0": {
        "r": 196,
        "g": 200,
        "b": 218
      },
      "surface1": {
        "r": 168,
        "g": 174,
        "b": 203
      },
      "surface_dim": {
        "r": 210,
        "g": 211,
        "b": 218
      },
      "overlay0": {
        "r": 137,
        "g": 144,
        "b": 179
      },
      "overlay1": {
        "r": 104,
        "g": 112,
        "b": 154
      },
      "text": {
        "r": 55,
        "g": 96,
        "b": 191
      },
      "subtext0": {
        "r": 97,
        "g": 114,
        "b": 176
      },
      "mauve": {
        "r": 120,
        "g": 71,
        "b": 189
      },
      "green": {
        "r": 88,
        "g": 117,
        "b": 57
      },
      "yellow": {
        "r": 140,
        "g": 108,
        "b": 62
      },
      "red": {
        "r": 245,
        "g": 42,
        "b": 101
      },
      "blue": {
        "r": 46,
        "g": 125,
        "b": 233
      },
      "teal": {
        "r": 17,
        "g": 140,
        "b": 116
      },
      "peach": {
        "r": 177,
        "g": 92,
        "b": 0
      }
    }
  },
  "dracula": {
    "name": "dracula",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 189,
        "g": 147,
        "b": 249
      },
      "panel_bg": {
        "r": 40,
        "g": 42,
        "b": 54
      },
      "surface0": {
        "r": 68,
        "g": 71,
        "b": 90
      },
      "surface1": {
        "r": 98,
        "g": 114,
        "b": 164
      },
      "surface_dim": {
        "r": 40,
        "g": 42,
        "b": 54
      },
      "overlay0": {
        "r": 98,
        "g": 114,
        "b": 164
      },
      "overlay1": {
        "r": 130,
        "g": 140,
        "b": 180
      },
      "text": {
        "r": 248,
        "g": 248,
        "b": 242
      },
      "subtext0": {
        "r": 210,
        "g": 210,
        "b": 220
      },
      "mauve": {
        "r": 255,
        "g": 121,
        "b": 198
      },
      "green": {
        "r": 80,
        "g": 250,
        "b": 123
      },
      "yellow": {
        "r": 241,
        "g": 250,
        "b": 140
      },
      "red": {
        "r": 255,
        "g": 85,
        "b": 85
      },
      "blue": {
        "r": 139,
        "g": 233,
        "b": 253
      },
      "teal": {
        "r": 139,
        "g": 233,
        "b": 253
      },
      "peach": {
        "r": 255,
        "g": 184,
        "b": 108
      }
    }
  },
  "nord": {
    "name": "nord",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 136,
        "g": 192,
        "b": 208
      },
      "panel_bg": {
        "r": 46,
        "g": 52,
        "b": 64
      },
      "surface0": {
        "r": 59,
        "g": 66,
        "b": 82
      },
      "surface1": {
        "r": 67,
        "g": 76,
        "b": 94
      },
      "surface_dim": {
        "r": 46,
        "g": 52,
        "b": 64
      },
      "overlay0": {
        "r": 76,
        "g": 86,
        "b": 106
      },
      "overlay1": {
        "r": 100,
        "g": 110,
        "b": 130
      },
      "text": {
        "r": 236,
        "g": 239,
        "b": 244
      },
      "subtext0": {
        "r": 216,
        "g": 222,
        "b": 233
      },
      "mauve": {
        "r": 180,
        "g": 142,
        "b": 173
      },
      "green": {
        "r": 163,
        "g": 190,
        "b": 140
      },
      "yellow": {
        "r": 235,
        "g": 203,
        "b": 139
      },
      "red": {
        "r": 191,
        "g": 97,
        "b": 106
      },
      "blue": {
        "r": 129,
        "g": 161,
        "b": 193
      },
      "teal": {
        "r": 143,
        "g": 188,
        "b": 187
      },
      "peach": {
        "r": 208,
        "g": 135,
        "b": 112
      }
    }
  },
  "gruvbox": {
    "name": "gruvbox",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 215,
        "g": 153,
        "b": 33
      },
      "panel_bg": {
        "r": 40,
        "g": 40,
        "b": 40
      },
      "surface0": {
        "r": 60,
        "g": 56,
        "b": 54
      },
      "surface1": {
        "r": 80,
        "g": 73,
        "b": 69
      },
      "surface_dim": {
        "r": 40,
        "g": 40,
        "b": 40
      },
      "overlay0": {
        "r": 146,
        "g": 131,
        "b": 116
      },
      "overlay1": {
        "r": 168,
        "g": 153,
        "b": 132
      },
      "text": {
        "r": 235,
        "g": 219,
        "b": 178
      },
      "subtext0": {
        "r": 213,
        "g": 196,
        "b": 161
      },
      "mauve": {
        "r": 211,
        "g": 134,
        "b": 155
      },
      "green": {
        "r": 184,
        "g": 187,
        "b": 38
      },
      "yellow": {
        "r": 250,
        "g": 189,
        "b": 47
      },
      "red": {
        "r": 251,
        "g": 73,
        "b": 52
      },
      "blue": {
        "r": 131,
        "g": 165,
        "b": 152
      },
      "teal": {
        "r": 142,
        "g": 192,
        "b": 124
      },
      "peach": {
        "r": 254,
        "g": 128,
        "b": 25
      }
    }
  },
  "gruvbox-light": {
    "name": "gruvbox-light",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 7,
        "g": 102,
        "b": 120
      },
      "panel_bg": {
        "r": 251,
        "g": 241,
        "b": 199
      },
      "surface0": {
        "r": 235,
        "g": 219,
        "b": 178
      },
      "surface1": {
        "r": 213,
        "g": 196,
        "b": 161
      },
      "surface_dim": {
        "r": 242,
        "g": 229,
        "b": 188
      },
      "overlay0": {
        "r": 146,
        "g": 131,
        "b": 116
      },
      "overlay1": {
        "r": 124,
        "g": 111,
        "b": 100
      },
      "text": {
        "r": 60,
        "g": 56,
        "b": 54
      },
      "subtext0": {
        "r": 80,
        "g": 73,
        "b": 69
      },
      "mauve": {
        "r": 143,
        "g": 63,
        "b": 113
      },
      "green": {
        "r": 121,
        "g": 116,
        "b": 14
      },
      "yellow": {
        "r": 181,
        "g": 118,
        "b": 20
      },
      "red": {
        "r": 157,
        "g": 0,
        "b": 6
      },
      "blue": {
        "r": 7,
        "g": 102,
        "b": 120
      },
      "teal": {
        "r": 66,
        "g": 123,
        "b": 88
      },
      "peach": {
        "r": 175,
        "g": 58,
        "b": 3
      }
    }
  },
  "one-dark": {
    "name": "one-dark",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 97,
        "g": 175,
        "b": 239
      },
      "panel_bg": {
        "r": 40,
        "g": 44,
        "b": 52
      },
      "surface0": {
        "r": 44,
        "g": 49,
        "b": 58
      },
      "surface1": {
        "r": 62,
        "g": 68,
        "b": 81
      },
      "surface_dim": {
        "r": 40,
        "g": 44,
        "b": 52
      },
      "overlay0": {
        "r": 92,
        "g": 99,
        "b": 112
      },
      "overlay1": {
        "r": 115,
        "g": 122,
        "b": 135
      },
      "text": {
        "r": 171,
        "g": 178,
        "b": 191
      },
      "subtext0": {
        "r": 150,
        "g": 156,
        "b": 168
      },
      "mauve": {
        "r": 198,
        "g": 120,
        "b": 221
      },
      "green": {
        "r": 152,
        "g": 195,
        "b": 121
      },
      "yellow": {
        "r": 229,
        "g": 192,
        "b": 123
      },
      "red": {
        "r": 224,
        "g": 108,
        "b": 117
      },
      "blue": {
        "r": 97,
        "g": 175,
        "b": 239
      },
      "teal": {
        "r": 86,
        "g": 182,
        "b": 194
      },
      "peach": {
        "r": 209,
        "g": 154,
        "b": 102
      }
    }
  },
  "one-light": {
    "name": "one-light",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 64,
        "g": 120,
        "b": 242
      },
      "panel_bg": {
        "r": 250,
        "g": 250,
        "b": 250
      },
      "surface0": {
        "r": 240,
        "g": 240,
        "b": 241
      },
      "surface1": {
        "r": 229,
        "g": 229,
        "b": 230
      },
      "surface_dim": {
        "r": 245,
        "g": 245,
        "b": 246
      },
      "overlay0": {
        "r": 160,
        "g": 161,
        "b": 167
      },
      "overlay1": {
        "r": 104,
        "g": 107,
        "b": 119
      },
      "text": {
        "r": 56,
        "g": 58,
        "b": 66
      },
      "subtext0": {
        "r": 104,
        "g": 107,
        "b": 119
      },
      "mauve": {
        "r": 166,
        "g": 38,
        "b": 164
      },
      "green": {
        "r": 80,
        "g": 161,
        "b": 79
      },
      "yellow": {
        "r": 193,
        "g": 132,
        "b": 1
      },
      "red": {
        "r": 228,
        "g": 86,
        "b": 73
      },
      "blue": {
        "r": 64,
        "g": 120,
        "b": 242
      },
      "teal": {
        "r": 1,
        "g": 132,
        "b": 188
      },
      "peach": {
        "r": 152,
        "g": 104,
        "b": 1
      }
    }
  },
  "solarized": {
    "name": "solarized",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 38,
        "g": 139,
        "b": 210
      },
      "panel_bg": {
        "r": 0,
        "g": 43,
        "b": 54
      },
      "surface0": {
        "r": 7,
        "g": 54,
        "b": 66
      },
      "surface1": {
        "r": 88,
        "g": 110,
        "b": 117
      },
      "surface_dim": {
        "r": 0,
        "g": 43,
        "b": 54
      },
      "overlay0": {
        "r": 88,
        "g": 110,
        "b": 117
      },
      "overlay1": {
        "r": 101,
        "g": 123,
        "b": 131
      },
      "text": {
        "r": 147,
        "g": 161,
        "b": 161
      },
      "subtext0": {
        "r": 131,
        "g": 148,
        "b": 150
      },
      "mauve": {
        "r": 211,
        "g": 54,
        "b": 130
      },
      "green": {
        "r": 133,
        "g": 153,
        "b": 0
      },
      "yellow": {
        "r": 181,
        "g": 137,
        "b": 0
      },
      "red": {
        "r": 220,
        "g": 50,
        "b": 47
      },
      "blue": {
        "r": 38,
        "g": 139,
        "b": 210
      },
      "teal": {
        "r": 42,
        "g": 161,
        "b": 152
      },
      "peach": {
        "r": 203,
        "g": 75,
        "b": 22
      }
    }
  },
  "solarized-light": {
    "name": "solarized-light",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 38,
        "g": 139,
        "b": 210
      },
      "panel_bg": {
        "r": 253,
        "g": 246,
        "b": 227
      },
      "surface0": {
        "r": 238,
        "g": 232,
        "b": 213
      },
      "surface1": {
        "r": 147,
        "g": 161,
        "b": 161
      },
      "surface_dim": {
        "r": 238,
        "g": 232,
        "b": 213
      },
      "overlay0": {
        "r": 147,
        "g": 161,
        "b": 161
      },
      "overlay1": {
        "r": 88,
        "g": 110,
        "b": 117
      },
      "text": {
        "r": 101,
        "g": 123,
        "b": 131
      },
      "subtext0": {
        "r": 131,
        "g": 148,
        "b": 150
      },
      "mauve": {
        "r": 211,
        "g": 54,
        "b": 130
      },
      "green": {
        "r": 133,
        "g": 153,
        "b": 0
      },
      "yellow": {
        "r": 181,
        "g": 137,
        "b": 0
      },
      "red": {
        "r": 220,
        "g": 50,
        "b": 47
      },
      "blue": {
        "r": 38,
        "g": 139,
        "b": 210
      },
      "teal": {
        "r": 42,
        "g": 161,
        "b": 152
      },
      "peach": {
        "r": 203,
        "g": 75,
        "b": 22
      }
    }
  },
  "kanagawa": {
    "name": "kanagawa",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 126,
        "g": 156,
        "b": 216
      },
      "panel_bg": {
        "r": 31,
        "g": 31,
        "b": 40
      },
      "surface0": {
        "r": 42,
        "g": 42,
        "b": 55
      },
      "surface1": {
        "r": 54,
        "g": 54,
        "b": 70
      },
      "surface_dim": {
        "r": 31,
        "g": 31,
        "b": 40
      },
      "overlay0": {
        "r": 114,
        "g": 113,
        "b": 105
      },
      "overlay1": {
        "r": 135,
        "g": 134,
        "b": 125
      },
      "text": {
        "r": 220,
        "g": 215,
        "b": 186
      },
      "subtext0": {
        "r": 200,
        "g": 195,
        "b": 170
      },
      "mauve": {
        "r": 149,
        "g": 127,
        "b": 184
      },
      "green": {
        "r": 118,
        "g": 148,
        "b": 106
      },
      "yellow": {
        "r": 192,
        "g": 163,
        "b": 110
      },
      "red": {
        "r": 195,
        "g": 64,
        "b": 67
      },
      "blue": {
        "r": 126,
        "g": 156,
        "b": 216
      },
      "teal": {
        "r": 127,
        "g": 180,
        "b": 202
      },
      "peach": {
        "r": 255,
        "g": 160,
        "b": 102
      }
    }
  },
  "kanagawa-lotus": {
    "name": "kanagawa-lotus",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 77,
        "g": 105,
        "b": 155
      },
      "panel_bg": {
        "r": 242,
        "g": 236,
        "b": 188
      },
      "surface0": {
        "r": 220,
        "g": 213,
        "b": 172
      },
      "surface1": {
        "r": 201,
        "g": 203,
        "b": 209
      },
      "surface_dim": {
        "r": 213,
        "g": 206,
        "b": 163
      },
      "overlay0": {
        "r": 160,
        "g": 156,
        "b": 172
      },
      "overlay1": {
        "r": 138,
        "g": 137,
        "b": 128
      },
      "text": {
        "r": 84,
        "g": 84,
        "b": 100
      },
      "subtext0": {
        "r": 67,
        "g": 67,
        "b": 108
      },
      "mauve": {
        "r": 98,
        "g": 76,
        "b": 131
      },
      "green": {
        "r": 111,
        "g": 137,
        "b": 78
      },
      "yellow": {
        "r": 119,
        "g": 113,
        "b": 63
      },
      "red": {
        "r": 200,
        "g": 64,
        "b": 83
      },
      "blue": {
        "r": 77,
        "g": 105,
        "b": 155
      },
      "teal": {
        "r": 78,
        "g": 140,
        "b": 162
      },
      "peach": {
        "r": 204,
        "g": 109,
        "b": 0
      }
    }
  },
  "rose-pine": {
    "name": "rose-pine",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 196,
        "g": 167,
        "b": 231
      },
      "panel_bg": {
        "r": 25,
        "g": 23,
        "b": 36
      },
      "surface0": {
        "r": 31,
        "g": 29,
        "b": 46
      },
      "surface1": {
        "r": 38,
        "g": 35,
        "b": 58
      },
      "surface_dim": {
        "r": 38,
        "g": 35,
        "b": 58
      },
      "overlay0": {
        "r": 110,
        "g": 106,
        "b": 134
      },
      "overlay1": {
        "r": 144,
        "g": 140,
        "b": 170
      },
      "text": {
        "r": 224,
        "g": 222,
        "b": 244
      },
      "subtext0": {
        "r": 200,
        "g": 197,
        "b": 220
      },
      "mauve": {
        "r": 196,
        "g": 167,
        "b": 231
      },
      "green": {
        "r": 49,
        "g": 116,
        "b": 143
      },
      "yellow": {
        "r": 246,
        "g": 193,
        "b": 119
      },
      "red": {
        "r": 235,
        "g": 111,
        "b": 146
      },
      "blue": {
        "r": 49,
        "g": 116,
        "b": 143
      },
      "teal": {
        "r": 156,
        "g": 207,
        "b": 216
      },
      "peach": {
        "r": 234,
        "g": 154,
        "b": 151
      }
    }
  },
  "rose-pine-dawn": {
    "name": "rose-pine-dawn",
    "appearance": "light",
    "palette": {
      "accent": {
        "r": 144,
        "g": 122,
        "b": 169
      },
      "panel_bg": {
        "r": 250,
        "g": 244,
        "b": 237
      },
      "surface0": {
        "r": 242,
        "g": 233,
        "b": 225
      },
      "surface1": {
        "r": 255,
        "g": 250,
        "b": 243
      },
      "surface_dim": {
        "r": 242,
        "g": 233,
        "b": 225
      },
      "overlay0": {
        "r": 152,
        "g": 147,
        "b": 165
      },
      "overlay1": {
        "r": 121,
        "g": 117,
        "b": 147
      },
      "text": {
        "r": 70,
        "g": 66,
        "b": 97
      },
      "subtext0": {
        "r": 121,
        "g": 117,
        "b": 147
      },
      "mauve": {
        "r": 144,
        "g": 122,
        "b": 169
      },
      "green": {
        "r": 40,
        "g": 105,
        "b": 131
      },
      "yellow": {
        "r": 234,
        "g": 157,
        "b": 52
      },
      "red": {
        "r": 180,
        "g": 99,
        "b": 122
      },
      "blue": {
        "r": 40,
        "g": 105,
        "b": 131
      },
      "teal": {
        "r": 86,
        "g": 148,
        "b": 159
      },
      "peach": {
        "r": 215,
        "g": 130,
        "b": 126
      }
    }
  },
  "vesper": {
    "name": "vesper",
    "appearance": "dark",
    "palette": {
      "accent": {
        "r": 255,
        "g": 199,
        "b": 153
      },
      "panel_bg": {
        "r": 26,
        "g": 26,
        "b": 26
      },
      "surface0": {
        "r": 35,
        "g": 35,
        "b": 35
      },
      "surface1": {
        "r": 40,
        "g": 40,
        "b": 40
      },
      "surface_dim": {
        "r": 16,
        "g": 16,
        "b": 16
      },
      "overlay0": {
        "r": 92,
        "g": 92,
        "b": 92
      },
      "overlay1": {
        "r": 126,
        "g": 126,
        "b": 126
      },
      "text": {
        "r": 255,
        "g": 255,
        "b": 255
      },
      "subtext0": {
        "r": 160,
        "g": 160,
        "b": 160
      },
      "mauve": {
        "r": 255,
        "g": 209,
        "b": 168
      },
      "green": {
        "r": 153,
        "g": 255,
        "b": 228
      },
      "yellow": {
        "r": 255,
        "g": 199,
        "b": 153
      },
      "red": {
        "r": 255,
        "g": 128,
        "b": 128
      },
      "blue": {
        "r": 176,
        "g": 176,
        "b": 176
      },
      "teal": {
        "r": 102,
        "g": 221,
        "b": 204
      },
      "peach": {
        "r": 255,
        "g": 199,
        "b": 153
      }
    }
  }
};

const aliases: Record<string, string> = {
  "catppuccin-mocha": "catppuccin",
  "latte": "catppuccin-latte",
  "light": "catppuccin-latte",
  "tokyonight": "tokyo-night",
  "tokyo-day": "tokyo-night-day",
  "tokyonight-day": "tokyo-night-day",
  "gruvbox-dark": "gruvbox",
  "onedark": "one-dark",
  "onelight": "one-light",
  "solarized-dark": "solarized",
  "lotus": "kanagawa-lotus",
  "rosepine": "rose-pine",
  "rosepine-dawn": "rose-pine-dawn",
  "dawn": "rose-pine-dawn"
};

export function copiedHerdrTheme(name: string): ResolvedThemeSnapshot | undefined {
  const normalized = name.toLowerCase().replace(/[ _]+/g, "-");
  const theme = themes[aliases[normalized] ?? normalized];
  return theme ? structuredClone(theme) : undefined;
}
